spring.application.name=productmanagementsystem1-4
spring.datasource.url=jdbc:postgresql://localhost:5432/skit
spring.datasource.username=postgres
spring.datasource.password=tiger
server.port=8080
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

